[profile.default]
#auto_detect_solc = false
solc-version = "0.8.25"
evm_version = "london"
optimizer = true
optimizer_runs = 1000000
cache = true
src = "src"
out = "out"
libs = ["lib"]
ffi = true
gas_reports = [
  "ERC20Core",
  "ERC721Core",
  "ERC1155Core"
]
ignored_warnings_from = ["node_modules", "lib", "test"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
